Fhir 40032, fhir 46287
HL7/davinci-deqm pull request #136
Opened 2024-07-31 23:04 UTC by dand9959

FHIR-40032 
    --- $care-gaps operation:
        Added subjectGroup, measureResource and measure IN parameters to $care-gaps operation
	    Changed $care-gaps "type" to "instance" so that the URL: [base]/Measure/[id]/$care-gaps is a valid option	
  ---	$deqm.evaluate-measure operation:
	    Renamed operation $deqm.evaluate-measure to $evaluate
	    Added subjectGroup parameter to $evaluate operation
	
 --- $deqm.collect-data operation
	    Added new operation:  $deqm.collect-data

FHIR-46287
	$evaluate operation:
		Added measureId, measureIdentifier, measureUrl, measureResource and report IN parameters
		Change cardinaltiy of measure IN parameter to 0.**

2024-08-01 00:18 UTC, dand9959 commented
[DEQM Operations Update.xlsx](https://github.com/user-attachments/files/16448244/DEQM.Operations.Update.xlsx)
This is the final spreadsheet from Matt Tiller outlining the change implemented (for FHIR-40032 and FHIR-46287 only)

2024-08-02 20:01 UTC, yanheras requested changes

2024-08-02 21:49 UTC, dand9959 commented
Regarding last commit:  [5de5cc1](https://github.com/HL7/davinci-deqm/pull/136/commits/5de5cc11d0011c827b989f561941f56ccb6495ff)

Updated links for manifest parameter target profile, and also for parameter programCode valueSet.  These links will result in QA errors at this point, but after dependencies are update, these will work.

2024-08-02 21:55 UTC, dand9959 commented
No documentation was provided for the aforementioned parameters.  Aside from the organization documentation suggested in comments here, further guidance/verbiage for the others can be easily added once provided.

2024-08-05 06:46 UTC, yanheras approved these changes

2024-08-06 13:38 UTC, p9g commented on archived/resources/OperationDefinition-deqm.evaluate-measure.xml
> +      <documentation value="The quality program being reported via canonical reference to ([Library{CQFMQualityProgram}](http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/library-cqfm)) indicati
https://jira.hl7.org/browse/FHIR-45309 renames CQFMQualityProgram to CQFMContentRelease, not yet applied

2024-08-06 13:39 UTC, p9g commented on archived/resources/OperationDefinition-deqm.evaluate-measure.xml
> +      <name value="program"/>
renamed "manifest"

2024-08-06 13:47 UTC, p9g commented on input/resources/OperationDefinition-evaluate.xml
> +        <targetProfile value="http://hl7.org/fhir/uv/crmi/StructureDefinition/crmi-manifestlibrary"/>
target profile should be CQFMContentRelease which derives from CRMI manifest.  See https://jira.hl7.org/browse/FHIR-45309 not yet applied

2024-08-06 13:58 UTC, p9g commented on input/resources/OperationDefinition-evaluate.xml
> +        <searchType value="token"/>
Where do we specify that this token is related to https://build.fhir.org/ig/HL7/cqf-measures/StructureDefinition-publishable-measure-cqfm-definitions.html#Measure.identifier:publisherIdentifier ?

2024-08-06 14:32 UTC, dand9959 commented
Thanks for all the comments. They are quite helpful.

We've encountered some technical issues on the forked branch that make the conflict resolution  in this PR  intractable.  After discussion, we have decided to create a new, clean PR to replace this one. The new PR will implement all of the changes reflected in this request, including additions per the comments here. The PR will be forthcoming on 08/06/2024

2024-08-06 18:26 UTC, dand9959 commented
**PLEASE BE ADVISED:**   
[Redo of PR136 fhir 40032 fhir 46287 by dand9959 · Pull Request #144 · HL7/davinci-deqm (github.com)](https://github.com/HL7/davinci-deqm/pull/144)  is the new (correct) PR to use instead of this one.

2024-08-06 20:33 UTC, p9g commented on input/resources/OperationDefinition-evaluate.xml
> +        <targetProfile value="http://hl7.org/fhir/uv/crmi/StructureDefinition/crmi-manifestlibrary"/>
This did not make it into PR144, perhaps because dependency is on QMIG ballot-2?

2024-08-07 12:35 UTC, p9g commented
Since PR144 is merged, this PR136 should be closed without merge

2024-08-07 13:41 UTC, closed without merging

2024-08-07 13:42 UTC, dand9959 commented
Closed without merge.  PR 144 was used instead.

2024-08-07 13:43 UTC, dand9959 commented
Done.
________________________________
From: Paul Denning ***@***.***>
Sent: Wednesday, August 7, 2024 6:36 AM
To: HL7/davinci-deqm ***@***.***>
Cc: Donahue, Dan ***@***.***>; Author ***@***.***>
Subject: Re: [HL7/davinci-deqm] Fhir 40032, fhir 46287 (PR #136)


Since PR144 is merged, this PR136 should be closed without merge

—
Reply to this email directly, view it on GitHub<https://github.com/HL7/davinci-deqm/pull/136#issuecomment-2273369881>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEC2ZFE6PZUXMHPR56E6WLLZQIIDLAVCNFSM6AAAAABLZMRMC6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZTGM3DSOBYGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>