FHIR-48462 Removed references to (previously removed) Quality Program…
HL7/davinci-deqm pull request #225
Opened 2024-11-06 22:12 UTC by dand9959

… value set.

StructureDefinition-extension-reportingProgram.json
	set value types to Identifier and canonical ("http://hl7.org/fhir/uv/crmi/StructureDefinition/crmi-manifestlibrary")
	QA shows 0 0 0 
	
OperationDefinition-evaluate.xml
    Removed programCode input
    Added input programIdentifier 0..1 string(token) The business identifier of the reporting program, for which measures are being evaluated. For example, downstream IGs could specify program identifiers. Mutually exclusive use with programUrl - it is an error to pass in both programIdentifier and programUrl parameters.
    Added input programUrl 0..1 canonical(CRMIManifestLibrary) 
	QA shows 0 0 0
	
	
Removed references to the quality-program valueset/codesystem from examples:
	MeasureReport-indv-measurereport02.json   QA: 1 0 0   (See note below re: these QA items)
	Measure-measure-exm108-example.json       QA: 1 1 0
	Measure-pi-example.json                   QA: 1 1 0 
	col-requirements-example.md (in 'includes' folder)
	
Removed quality program examples from care-gaps-operation-example.md (in includes folder)
	
QA reports a warning and error for each new reference to http://hl7.org/fhir/us/cqfmeasures/CodeSystem/intended-venue-codes:
		input\examples\Measure-measure-exm108-example.json
		input\examples\Measure-measure-exm108-example.json	
		input\examples\Measure-pi-example.json
	These will go away once QM IG STU5 is published and we update the DEQM dependency accordingly.
	Similarly, the error "Canonical URL 'http://hl7.org/fhir/us/cqfmeasures/Library/Quality-Program-Example' does not resolve"
	shows up in MeasureReport-indv-measurereport02.  This resovles when dependency on QM IG is updated.

2025-01-20 07:43 UTC, yanheras requested changes
See comments

2025-01-20 07:43 UTC, yanheras commented on input/resources/OperationDefinition-evaluate.xml
> +        <documentation value="Mutually exclusive use with programUrl - it is an error to pass in both programIdentifier and programUrl parameters."/>
It looks like the resolution has typo. The documentation here for programUrl should be "Mutually exclusive use with programIdentifier .... " instead of programUrl.

2025-01-20 07:43 UTC, yanheras commented on input/resources/OperationDefinition-evaluate.xml
> +        <type value="canonical"/>
For programUrl, it needs to add targetProfile that points to CRMIManifestLibrary. 
The resolution says "programUrl 0..1 canonical(CRMIManifestLibrary)", and also in resolution to update evaluate operation "similar to the approach used for measure".
Here is the link to $evaluate-measure on Measure that has the url parameter as canonical(PlanDefinition): https://www.hl7.org/fhir/operation-measure-evaluate-measure.json.html

2025-01-20 07:43 UTC, yanheras commented on input/resources/StructureDefinition-extension-reportingProgram.json
> +            "targetProfile": ["http://hl7.org/fhir/uv/crmi/StructureDefinition/crmi-manifestlibrary"]
note: since the dependencies haven't been updated, this points to the snapshot still. Does not need to be updated as part of this PR, just adding as a note.

2025-01-28 21:47 UTC, dand9959 commented on input/resources/OperationDefinition-evaluate.xml
> +        <documentation value="Mutually exclusive use with programUrl - it is an error to pass in both programIdentifier and programUrl parameters."/>
Fixed in commit [36c1917](https://github.com/HL7/davinci-deqm/pull/225/commits/36c1917294c9e19a0f0f83ee3a6d83c08d308b94)

2025-01-28 21:47 UTC, dand9959 commented on input/resources/OperationDefinition-evaluate.xml
> +        <type value="canonical"/>
Fixed in commit [36c1917](https://github.com/HL7/davinci-deqm/pull/225/commits/36c1917294c9e19a0f0f83ee3a6d83c08d308b94)

2025-02-11 11:50 UTC, yanheras approved these changes

2025-02-11 11:50 UTC, merged