Fhir 47535 version needed in url for measurereport.measure
HL7/davinci-deqm pull request #226
Opened 2024-11-12 19:53 UTC by bryantaustin13

https://jira.hl7.org/browse/FHIR-47535
![Screenshot 2024-11-12 at 12 38 51 PM](https://github.com/user-attachments/assets/8a03e300-1e3d-4bbe-803c-c56a7ae40ae7)
![Screenshot 2024-11-12 at 12 39 15 PM](https://github.com/user-attachments/assets/ff46eb18-cb59-49e9-a42b-b9ed075c5a3b)
![Screenshot 2024-11-12 at 12 40 51 PM](https://github.com/user-attachments/assets/ad96f331-b5cb-49a7-8286-f9d4b68563ce)

The errors for [input/resources/StructureDefinition-indv-measurereport-deqm.xml](http://localhost:63342/davinci-deqm-local/output/StructureDefinition-indv-measurereport-deqm.html) are a separate issue.

2025-01-20 08:52 UTC, yanheras requested changes
See comments.

2025-01-20 08:52 UTC, yanheras commented on input/examples/Bundle-multiple-summ-report.json
> +        "measure": "http://hl7.org/fhir/us/davinci-deqm/Measure/measure-exm130-example|5.0.0-ballot",
For measure-exm130-example (for all examples), the version used here should match what's defined in the measure-exm130-example of using 5.0.0-ballot or 5.0.0. 

  "url": "http://hl7.org/fhir/us/davinci-deqm/Measure/measure-exm130-example",
  "version": "2.0.0",

2025-01-20 08:52 UTC, yanheras commented on input/examples/Bundle-multiple-summ-report.json
> +        "measure": "http://hl7.org/fhir/us/davinci-deqm/Measure/measure-mrp-example|4.0.0",
The measure example in the IG has has version 1.1.1
    "url": "http://hl7.org/fhir/us/davinci-deqm/Measure/measure-mrp-example",
    "version": "1.1.1",

2025-01-20 08:52 UTC, yanheras commented on input/resources/StructureDefinition-indv-measurereport-deqm.xml
> +      <condition value="deqm-0"/>
Tested by removing version "|5.0.0" from the MeasureReport-indv-measurereport01.json file, see below
"measure": "http://hl7.org/fhir/us/davinci-deqm/Measure/measure-mrp-example",
It does not look like the deqm-0 constraint is triggered. QA report shows 0 errors/warnings for this file.

2025-02-05 17:59 UTC, bryantaustin13 commented
Comments should be addressed. I did ensure that the constraints worked.

2025-02-11 13:09 UTC, merged